# Generated by Django 2.1.3 on 2018-11-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streat', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=6)),
                ('neighborhood', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
            ],
        ),
    ]
