# Generated by Django 2.1.3 on 2018-11-13 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_choice', models.CharField(choices=[('P', 'Product'), ('S', 'Service')], max_length=1)),
                ('nome', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('commission', models.FloatField(validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.AlterField(
            model_name='seller',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
