# Generated by Django 2.1.3 on 2018-11-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181113_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productservice',
            old_name='nome',
            new_name='name',
        ),
    ]
