# Generated by Django 2.1.3 on 2018-11-13 16:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181113_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 11, 13, 16, 52, 13, 757417, tzinfo=utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Client')),
                ('product_service', models.ManyToManyField(to='core.ProductService')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Seller')),
            ],
        ),
    ]
