# Generated by Django 2.1.3 on 2018-11-13 17:16

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='commission',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(0.1), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 17, 16, 5, 44728, tzinfo=utc)),
        ),
    ]
