# Generated by Django 2.1.3 on 2018-11-14 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181113_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 13, 16, 20, 135772, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
