# Generated by Django 2.1.3 on 2018-11-15 17:53

import core.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20181114_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[core.validators.validate_cpf_len]),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=11, validators=[core.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 17, 53, 31, 439741, tzinfo=utc)),
        ),
    ]
